- hosts: server

  remote_user: root

  vars_files:
    - group_vars/all/vault.yml

  tasks:
    - name: Add user
      user:
        name: "{{ user_name }}"
        state: present
        password: "{{ user_password | password_hash('sha512') }}"
        update_password: on_create
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Copy authorized keys from root to the user
      synchronize:
        src: /root/.ssh
        dest: "/home/{{ user_name }}"
        archive: true
        rsync_opts:
          - "--chown={{ user_name }}:{{ user_name }}"
      delegate_to: "{{ inventory_hostname }}"

    - name: Enable UFW firewall and allow ssh
      ufw:
        state: enabled
        rule: allow
        name: OpenSSH

    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: restart sshd

    - name: Install fail2ban
      ansible.builtin.apt:
        name: fail2ban
        update_cache: yes

    - name: Copy jail.local to the remote server
      ansible.builtin.copy:
        src: files/jail.local
        dest: /etc/fail2ban/jail.local
        mode: '0644'
      notify: restart fail2ban

  handlers:
    - name: restart sshd
      ansible.builtin.service:
        name: ssh
        state: reloaded

    - name: restart fail2ban
      ansible.builtin.service:
        name: fail2ban
        enabled: yes
        state: reloaded
