initial-setup:
	ansible-playbook -i inventory.ini --vault-password-file ./vault_password.txt initial.yml

docker-setup:
	ansible-playbook -i inventory.ini --vault-password-file ./vault_password.txt docker.yml
